### ISSUE TITLE
about "container_abcs' from 'torch._six"

### ISSUE THREAD

**Issue by tjleoos** [rusty1s/pytorch_geometric#2755]
From now on, we recommend using our discussion forum (https://github.com/rusty1s/pytorch_geometric/discussions) for general questions.

## ❓ Questions & Help

Hi, today I have an error when running PytorchGeo. Its says: cannot import name 'container_abcs' from 'torch._six'.
I've installed the CUDA and pytorch series as recommended in the website. And I don't know what to do.
Do you have any ideas about this problems?
Thank you!
![the error](https://user-images.githubusercontent.com/66160700/122626159-653f6200-d0db-11eb-958e-f74708ec096c.png)

**Comment by rusty1s** [comment]
You need to install PyTorch Geometric 1.7.1 to work with PyTorch 1.9.0.

**Comment by tjleoos** [comment]
> You need to install PyTorch Geometric 1.7.1 to work with PyTorch 1.9.0.

Thank you! Problems solved :)

**Comment by pflashgary** [comment]
Hi, running into the same issue. This is what I did:

```python
import torch
from IPython.display import clear_output
pt_version = torch.__version__
print(pt_version)
1.10.0+cu111
```

Then

```sh
pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-${pt_version}.html
pip install torch-sparse -f https://pytorch-geometric.com/whl/torch-${pt_version}.html
pip install torch-cluster -f https://pytorch-geometric.com/whl/torch-${pt_version}.html
pip install torch-spline-conv -f https://pytorch-geometric.com/whl/torch-${pt_version}.html
pip install torch-geometric
pip install torch-geometric-temporal
```
After successfully installing all packages:

```python
from torch_geometric_temporal.dataset import METRLADatasetLoader
ImportError: cannot import name 'container_abcs' from 'torch._six' 
```

**Comment by rusty1s** [comment]
This looks like a problem with PyTorch Geometric Temporal. Please report the issue there :)

**Comment by pflashgary** [comment]
Thanks heaps Matthias. You are doing an amazing job supporting the graph community here :clap: 

I have created an [one](https://github.com/benedekrozemberczki/pytorch_geometric_temporal/issues/127).  As you mentioned the issue is PyTorch Geometric Temporal. It looks to me `pip install torch-geometric-temporal` uninstalls the latest version of torch-geometric (`torch-geometric-2.0.3`) and installs `torch-geometric-1.7.0`, hence the ImportError.

**Comment by rusty1s** [comment]
I think this was fixed in 1.7.1. As an alternative, you can modify the source code of the installed PyG package directly and simply remove [these lines](https://github.com/pyg-team/pytorch_geometric/blob/1.7.0/torch_geometric/data/dataloader.py#L26-L31)

**Comment by pflashgary** [comment]
Yes it is all working with geometric >= 1.7.1 not the temporal. Thanks I'll try your alternative.
