### ISSUE TITLE
How to deal with a big graph in PyG?

### ISSUE THREAD

**Issue by quqxui** [rusty1s/pytorch_geometric#1266]
## ❓ Questions & Help
Hi, i have a huge single graph, the number of notes are about 160K,  and the adjacency matrix is 160k*160k.  Does PyG have any solutions for big graph like that? 
Thank you very much!!

**Comment by kkonevets** [comment]
Is your adjacency matrix sparse? If so, PyG has a sparse matrix storage, maybe it is a default one now.
Another thing you could do is to split the graph on subgraphs and process each separately. The way you split depends on your task.
Some algorithms assume sampling under hood, so you can pre sample nodes for subgraphs reducing total amount of required memory.

**Comment by rusty1s** [comment]
If your graph does not fit into GPU memory at once, you need to look at sampling strategies like `NeighborSampler` (`examples/reddit.py`) or `ClusterLoader` (`examples/cluster_gcn`).

**Comment by quqxui** [comment]
> If your graph does not fit into GPU memory at once, you need to look at sampling strategies like `NeighborSampler` (`examples/reddit.py`) or `ClusterLoader` (`examples/cluster_gcn`).

Thanks for your advice, i have tired the  (`examples/reddit.py`)  & (`examples/cluster_gcn`). But there are something wrong about the `NeighborSampler`.

`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-6ebc6353a8d2> in <module>()
     13 train_loader = NeighborSampler(data.edge_index, node_idx=data.train_mask,
     14                                sizes=[25, 10], batch_size=1024, shuffle=True,
---> 15                                num_workers=12)
     16 subgraph_loader = NeighborSampler(data.edge_index, node_idx=None, sizes=[-1],
     17                                   batch_size=1024, shuffle=False,

/usr/local/lib/python3.6/dist-packages/torch_geometric/data/sampler.py in __init__(self, edge_index, sizes, node_idx, num_nodes, flow, **kwargs)
     79         N = int(edge_index.max() + 1) if num_nodes is None else num_nodes
     80         edge_attr = torch.arange(edge_index.size(1))
---> 81         adj = SparseTensor.from_edge_index(edge_index, edge_attr, (N, N),
     82                                            is_sorted=False)
     83         adj = adj.t() if flow == 'source_to_target' else adj

AttributeError: type object 'SparseTensor' has no attribute 'from_edge_index'`

My environment is 
` torch_cluster==latest+cu101 torch-scatter==latest+cu101 torch-sparse==latest+cu101 torch_spline_conv==latest+cu101 
torch-geometric
torch==1.4.0 torchvision==0.5.0
` on google colab. 

thanks for answering.

**Comment by quqxui** [comment]
i found it works well on `pytorch1.5.0` , thank u for reply.
