### ISSUE TITLE
Running examples of gat.py and super_gat.py on cuda

### ISSUE THREAD

**Issue by VioletPepper** [rusty1s/pytorch_geometric#2831]
## 🐛 Bug

When I ran gat.py and super_gat.py examples on cpu, it worked out fine. However, when I changed the device into cuda, there emerged the error  'RuntimeError: nvrtc: error: invalid value for --gpu-architecture (-arch)'. It seemed that the softmax operation called in message() cannot match the gpu architecture, which kind of confused me. The detailed environment and bug reports of mine are listed below. Looking forward to your reply. Thank you!

## To Reproduce

Simply run gat.py or super_gat.py provided in pytorch_geometric/examples/

The tracebacks and error messages are shown below:
'''
Traceback (most recent call last):
  File "/others/gat.py", line 57, in <module>
    train(data)
  File "/others/gat.py", line 40, in train
    out = model(data.x, data.edge_index)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/others/gat.py", line 28, in forward
    x = self.conv2(x, data.edge_index)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch_geometric/nn/conv/gat_conv.py", line 152, in forward
    out = self.propagate(edge_index, x=(x_l, x_r),
  File "/opt/conda/lib/python3.8/site-packages/torch_geometric/nn/conv/message_passing.py", line 237, in propagate
    out = self.message(**msg_kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch_geometric/nn/conv/gat_conv.py", line 180, in message
    alpha = softmax(alpha, index, ptr, size_i)
RuntimeError: nvrtc: error: invalid value for --gpu-architecture (-arch)

nvrtc compilation failed: 

#define NAN __int_as_float(0x7fffffff)
#define POS_INFINITY __int_as_float(0x7f800000)
#define NEG_INFINITY __int_as_float(0xff800000)

template<typename T>
__device__ T maximum(T a, T b) {
  return isnan(a) ? a : (a > b ? a : b);
}

template<typename T>
__device__ T minimum(T a, T b) {
  return isnan(a) ? a : (a < b ? a : b);
}

extern "C" __global__
void func_1(float* t0, float* t1, float* aten_exp_flat) {
{
  if (512 * blockIdx.x + threadIdx.x<106112 ? 1 : 0) {
    float v = __ldg(t0 + 512 * blockIdx.x + threadIdx.x);
    float v_1 = __ldg(t1 + 512 * blockIdx.x + threadIdx.x);
    aten_exp_flat[512 * blockIdx.x + threadIdx.x] = expf(v - v_1);
  }
}
}

Process finished with exit code 1

'''

## Expected behavior

The scripts should run without issues

## Environment

* OS: Linux version 5.9.11-3-MANJARO 
* Python version: 3.8.3
* PyTorch version: 1.7.0
* CUDA/cuDNN version: 11.0

**Comment by rusty1s** [comment]
Seems to be related to CUDA 11.0 and PyTorch 1.7.0, see [here](https://github.com/pytorch/pytorch/issues/47658). I think either upgrading PyTorch or CUDA should help. Other-wise, please report your GPU and driver version.

**Comment by VioletPepper** [comment]
After I upgraded CUDA to 11.1 and PyTorch to 1.8.0, there emerged a similar error: `RuntimeError: nvrtc: error: failed to open libnvrtc-builtins.so.11.1. Make sure that libnvrtc-builtins.so.11.1 is installed correctly.`  Tracebacks are the same as before. My driver version is 455.45.01 and GPU is GeForce RTX 3090. I wonder if it is related to my CUDA and how I can fix it. Thank you！

**Comment by rusty1s** [comment]
Is your CUDA environment set up correctly? In particular, you should make sure that your CUDA folder is linked in `LD_LIBRARY_PATH`, see https://github.com/chainer/chainer/issues/4813.

**Comment by VioletPepper** [comment]
I found my CUDA folder fails to be linked in LD_LIBRARY_PATH. Thank you very much for the patient help!
